const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            images: '/images/product-1.jpg',
            price: 120,
            countInStock: 12,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Adidas Slim Shirt',
            category: 'Shirts',
            images: '/images/product-2.jpg',
            price: 100,
            countInStock: 5,
            brand: 'Adidas',
            rating: 4,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Lacoste Slim Shirt',
            category: 'Shirts',
            images: '/images/product-3.jpg',
            price: 220,
            countInStock: 15,
            brand: 'Lacoste',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Nike Slim Pants',
            category: 'Pantss',
            images: '/images/product-4.jpg',
            price: 137,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Puma Slim Pants',
            category: 'Pants',
            images: '/images/product-5.jpg',
            price: 60,
            countInStock: 20,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Adidas Slim Pants',
            category: 'Pantss',
            images: '/images/product-6.jpg',
            price: 139,
            countInStock: 0,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
    ]
}

export default data;